stages:
  - buildImage

variables:
  DOCKER_IMAGE_NAME: "tapsellorg/android-sdk"
  DOCKERHUB_USER: "tapsell"

buildDockerImage:
  stage: buildImage
  only:
    refs:
      - master
      - tags
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USER" --password-stdin
  script:
    - docker buildx create --use
    - |
      if [ "$CI_COMMIT_BRANCH" = "master" ]; then
        IMAGE_TAG="latest"
      elif [ -n "$CI_COMMIT_TAG" ]; then
        IMAGE_TAG="$CI_COMMIT_TAG"
      else
        echo "Error: No valid tag found for the image."
        exit 1
      fi
    - docker buildx build --platform linux/amd64 -t "$DOCKER_IMAGE_NAME:$IMAGE_TAG" --push .
