stages:
  - buildImage

variables:
  GIT_STRATEGY: clone

buildDockerImage:
  stage: buildImage
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [ "" ]

  before_script:
    - export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64

  script:
    - imageName="tapsellorg/android-sdk:$CI_COMMIT_TAG"
    - echo "$imageName"
    - mv $KANIKO_CONFIG /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $imageName
  
  only:
    - master
    - /v[0-9|\.]+[-a-z0-9]*/
  except:
    - branches
  tags: 
    - hetzner